curl --location --request POST 'https://dev-wesleyoliveirap.us.auth0.com/oauth/token' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'client_id=EDTyWxYo9fMNPMVZLf8NRv3O018QFSSe' \
--data-urlencode 'username=codingly@mailinator.com' \
--data-urlencode 'password=123Mudar' \
--data-urlencode 'grant_type=password' \
--data-urlencode 'scope=openid'